In [61]:
import pandas as pd
from pandas.io.parquet import to_parquet

In [2]:
df = pd.read_csv(r'C:\Users\RISHABH\OneDrive\Desktop\My_Learning\ML with python and sciket_learn\Lesson 7 - Machine Learning Project from Scratch\processed_data\comp_train.csv')

In [3]:
test_df = pd.read_csv(r'C:\Users\RISHABH\OneDrive\Desktop\My_Learning\ML with python and sciket_learn\Lesson 7 - Machine Learning Project from Scratch\processed_data\process_test.csv')

In [4]:
df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,4.0,2014-12-06 20:36:22+00:00,-73.979810,40.751904,-73.979450,40.755481,1.0
1,8.0,2013-01-17 17:22:00+00:00,0.000000,0.000000,0.000000,0.000000,2.0
2,8.9,2011-06-15 18:07:00+00:00,-73.996330,40.753223,-73.978900,40.766963,3.0
3,6.9,2009-12-14 12:33:00+00:00,-73.982430,40.745747,-73.982430,40.745747,1.0
4,7.0,2013-11-06 11:26:54+00:00,-73.959060,40.781060,-73.962060,40.768604,1.0
...,...,...,...,...,...,...,...
552445,45.0,2014-02-06 23:59:45+00:00,-73.973590,40.747670,-73.999916,40.602893,1.0
552446,22.5,2015-01-05 15:29:08+00:00,-73.935930,40.799656,-73.985710,40.726952,2.0
552447,4.5,2013-02-17 22:27:00+00:00,-73.992530,40.748620,-73.998436,40.740142,1.0
552448,14.5,2013-01-27 12:41:00+00:00,-74.012115,40.706635,-73.988720,40.756217,1.0
552449,6.0,2014-10-18 07:51:00+00:00,-73.997680,40.724380,-73.994150,40.717797,1.0

In [5]:
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1.0
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986860,40.719383,-73.998886,40.739201,1.0
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982520,40.751260,-73.979650,40.746139,1.0
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981160,40.767807,-73.990450,40.751635,1.0
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966050,40.789776,-73.988560,40.744427,1.0
...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955640,40.780388,6.0
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945510,40.803600,-73.960210,40.776371,6.0
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726610,-73.789740,40.647011,6.0
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985570,40.735430,-73.939180,40.801731,6.0
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988020,40.754070,-74.000280,40.759220,6.0

### Exploring the Dataset

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552450 entries, 0 to 552449
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   fare_amount        552450 non-null  float64
 1   pickup_datetime    552450 non-null  str
 2   pickup_longitude   552450 non-null  float64
 3   pickup_latitude    552450 non-null  float64
 4   dropoff_longitude  552450 non-null  float64
 5   dropoff_latitude   552450 non-null  float64
 6   passenger_count    552450 non-null  float64
dtypes: float64(6), str(1)
memory usage: 42.7 MB

In [7]:
df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,552450.000000,552450.000000,552450.000000,552450.000000,552450.000000,552450.000000
mean,11.354059,-72.497069,39.910494,-72.504346,39.934257,1.684983
std,9.811924,11.618246,8.061115,12.074345,9.255058,1.337664
min,-52.000000,-1183.362800,-3084.490200,-3356.729700,-2073.150613,0.000000
25%,6.000000,-73.992020,40.734875,-73.991425,40.733988,1.000000
50%,8.500000,-73.981820,40.752620,-73.980180,40.753102,1.000000
75%,12.500000,-73.967155,40.767036,-73.963740,40.768060,2.000000
max,499.000000,2420.209500,404.983340,2467.752700,3351.403027,208.000000

In [8]:
test_df.describe()

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000
mean,-73.974722,40.751041,-73.973657,40.751743,1.671273
std,0.042774,0.033542,0.039072,0.035435,1.278747
min,-74.252190,40.573143,-74.263245,40.568973,1.000000
25%,-73.992500,40.736125,-73.991250,40.735254,1.000000
50%,-73.982325,40.753050,-73.980015,40.754065,1.000000
75%,-73.968013,40.767113,-73.964061,40.768757,2.000000
max,-72.986534,41.709557,-72.990970,41.696683,6.000000

In [9]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9914 entries, 0 to 9913
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   key                9914 non-null   str
 1   pickup_datetime    9914 non-null   str
 2   pickup_longitude   9914 non-null   float64
 3   pickup_latitude    9914 non-null   float64
 4   dropoff_longitude  9914 non-null   float64
 5   dropoff_latitude   9914 non-null   float64
 6   passenger_count    9914 non-null   float64
dtypes: float64(5), str(2)
memory usage: 1.0 MB

In [10]:
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1.0
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986860,40.719383,-73.998886,40.739201,1.0
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982520,40.751260,-73.979650,40.746139,1.0
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981160,40.767807,-73.990450,40.751635,1.0
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966050,40.789776,-73.988560,40.744427,1.0
...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955640,40.780388,6.0
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945510,40.803600,-73.960210,40.776371,6.0
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726610,-73.789740,40.647011,6.0
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985570,40.735430,-73.939180,40.801731,6.0
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988020,40.754070,-74.000280,40.759220,6.0

In [11]:
df.isnull().sum().sort_values(ascending=False)

fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [12]:
test_df.isnull().sum().sort_values(ascending=False)

key                  0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [13]:
# train dataset
df.pickup_datetime.min() , df.pickup_datetime.max()

('2009-01-01 00:11:46+00:00', '2015-06-30 23:59:54+00:00')

Observations about training data:

- 550k+ rows, as expected
- No missing data (in the sample)
- `fare_amount` ranges from \$-52.0 to \$499.0
- `passenger_count` ranges from 0 to 208
- There seem to be some outliers in the `passenger_count`
- There seem to be some errors in the latitude & longitude values
- Dates range from 1st Jan 2009 to 30th June 2015
- The dataset takes up ~19 MB of space in the RAM

We may need to deal with outliers and data entry errors before we train our model.

In [14]:
# test dataset
test_df.pickup_datetime.min(), test_df.pickup_datetime.max()

('2009-01-01 11:04:24+00:00', '2015-06-30 20:03:50+00:00')

Some observations about the test set:

- 9914 rows of data
- No missing values
- No obvious data entry errors
- 1 to 6 passengers (we can limit training data to this range)
- Latitudes lie between 40 and 42
- Longitudes lie between -75 and -72
- Pickup dates range from Jan 1st 2009 to Jun  30th 2015 (same as training set)

We can use the ranges of the test set to drop outliers/invalid data from the training set.

### Split Training & Validation Set

We'll set aside 20% of the training data as the validation set, to evaluate the models we train on previously unseen data.

Since the test set and training set have the same date ranges, we can pick a random 20% fraction.

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
train_df , val_df = train_test_split(df , test_size=0.2 , random_state=42)

In [17]:
len(train_df), len(val_df)

(441960, 110490)

In [18]:
df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count'],
      dtype='str')

In [19]:
input_cols = ['pickup_longitude', 'pickup_latitude','dropoff_longitude', 'dropoff_latitude', 'passenger_count']

In [20]:
target_cols = 'fare_amount'

In [21]:
train_inputs = train_df[input_cols]

In [22]:
train_targets = train_df[target_cols]

In [23]:
train_inputs

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
353352,-73.993650,40.741543,-73.977974,40.742352,4.0
360070,-73.993805,40.724580,-73.993805,40.724577,1.0
372609,-73.959160,40.780750,-73.969120,40.761231,1.0
550895,-73.952190,40.783950,-73.978645,40.772603,1.0
444151,-73.977110,40.746834,-73.991104,40.750403,2.0
...,...,...,...,...,...
110268,-73.987150,40.750633,-73.979070,40.763167,1.0
259178,-73.972660,40.764040,-74.013176,40.707841,2.0
365838,-73.991980,40.749767,-73.989845,40.720552,3.0
131932,-73.969055,40.761400,-73.990814,40.751327,1.0
121958,-73.983040,40.742140,-74.002510,40.727650,1.0

In [24]:
train_targets

353352     6.0
360070     3.7
372609    10.0
550895     8.9
444151     7.3
          ...
110268     9.3
259178    18.5
365838    10.1
131932    10.9
121958     9.5
Name: fare_amount, Length: 441960, dtype: float64

In [25]:
val_inputs = val_df[input_cols]

In [26]:
val_targets = val_df[target_cols]

In [27]:
val_inputs

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
15971,-73.995834,40.759190,-73.973680,40.739086,1.0
149839,-73.977390,40.738335,-73.976140,40.751204,1.0
515867,-73.983910,40.749470,-73.787170,40.646643,1.0
90307,-73.790794,40.643463,-73.972250,40.690180,1.0
287032,-73.976590,40.761944,-73.991460,40.750309,2.0
...,...,...,...,...,...
467556,-73.968570,40.761240,-73.983406,40.750020,3.0
19482,-73.986725,40.755920,-73.985855,40.731170,1.0
186063,0.000000,0.000000,0.000000,0.000000,1.0
382260,-73.980060,40.760334,-73.872590,40.774298,1.0
18838,-73.955410,40.782417,-73.960434,40.767666,1.0

In [28]:
val_targets

15971     14.00
149839     6.50
515867    49.57
90307     49.70
287032     8.50
          ...
467556     6.10
19482      7.30
186063     4.50
382260    32.90
18838     11.50
Name: fare_amount, Length: 110490, dtype: float64

In [29]:
test_inputs = test_df[input_cols]

In [30]:
test_inputs

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,-73.973320,40.763805,-73.981430,40.743835,1.0
1,-73.986860,40.719383,-73.998886,40.739201,1.0
2,-73.982520,40.751260,-73.979650,40.746139,1.0
3,-73.981160,40.767807,-73.990450,40.751635,1.0
4,-73.966050,40.789776,-73.988560,40.744427,1.0
...,...,...,...,...,...
9909,-73.968124,40.796997,-73.955640,40.780388,6.0
9910,-73.945510,40.803600,-73.960210,40.776371,6.0
9911,-73.991600,40.726610,-73.789740,40.647011,6.0
9912,-73.985570,40.735430,-73.939180,40.801731,6.0
9913,-73.988020,40.754070,-74.000280,40.759220,6.0

## 4. Train Hardcoded & Baseline Models

- Hardcoded model: always predict average fare
- Baseline model: Linear regression

In [31]:
import numpy as np

In [32]:
class MeanRegressor:
    def fit(self, inputs, targets):
        self.mean = targets.mean()

    def predict(self , inputs):
        return np.full(inputs.shape[0], self.mean)

In [33]:
mean_model = MeanRegressor()

In [34]:
mean_model.fit(train_inputs, train_targets)

In [35]:
mean_model.mean

np.float64(11.354714227531904)

In [36]:
train_preds_mean = mean_model.predict(train_inputs)

In [37]:
val_preds_mean = mean_model.predict(val_inputs)

In [38]:
train_preds_mean

array([11.35471423, 11.35471423, 11.35471423, ..., 11.35471423,
       11.35471423, 11.35471423], shape=(441960,))

In [39]:
val_preds_mean

array([11.35471423, 11.35471423, 11.35471423, ..., 11.35471423,
       11.35471423, 11.35471423], shape=(110490,))

In [40]:
from sklearn.metrics import root_mean_squared_error

In [41]:
train_rmse = root_mean_squared_error(train_preds_mean, train_targets)

In [42]:
val_rmse = root_mean_squared_error(val_preds_mean, val_targets)

In [43]:
train_rmse, val_rmse

(9.789781929882418, 9.899954129550743)

Our dumb hard-coded model is off by `$9.899` on average, which is pretty bad considering the average fare is `$11.35`.

### Train & Evaluate Baseline Model

We'll traina linear regression model as our baseline, which tries to express the target as a weighted sum of the inputs.

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
linreg_model = LinearRegression()

In [46]:
linreg_model.fit(train_inputs, train_targets)

LinearRegression()

In [47]:
train_preds_lr = linreg_model.predict(train_inputs)
train_preds_lr

array([11.54623679, 11.28460945, 11.28413938, ..., 11.45891671,
       11.28428002, 11.28444732], shape=(441960,))

In [48]:
val_preds_lr = linreg_model.predict(val_inputs)
val_preds_lr

array([11.28432792, 11.28449547, 11.28478052, ..., 11.80449937,
       11.28443341, 11.28413231], shape=(110490,))

In [49]:
train_preds_lr_rmse = root_mean_squared_error(train_preds_lr , train_targets)

In [50]:
val_preds_lr_rmse = root_mean_squared_error(val_preds_lr, val_targets)

In [51]:
train_preds_lr_rmse, val_preds_lr_rmse

(9.78863260628024, 9.898088158697032)

The linear regression model is off by $9.898, which isn't much better than simply predicting the average.

This is mainly because the training data (geocoordinates) is not in a format that's useful for the model, and we're not using one of the most important columns: pickup date & time.

However, now we have a baseline that our other models should ideally beat.

## 6. Feature Engineering

- Extract parts of date
- Remove outliers & invalid data
- Add distance between pickup & drop
- Add distance from landmarks

Exercise: We're going to apply all of the above together, but you should observer the effect of adding each feature individually.

In [52]:
def adddateparts(df, col):
    df[col] = pd.to_datetime(df[col], errors='coerce')

    df[col + '_year'] = df[col].dt.year
    df[col + '_month'] = df[col].dt.month
    df[col + '_day'] = df[col].dt.day
    df[col + '_weekday'] = df[col].dt.weekday
    df[col + '_hour'] = df[col].dt.hour

In [53]:
adddateparts(train_df , 'pickup_datetime')

In [54]:
train_df.head()

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
353352,6.0,2015-04-12 03:40:38+00:00,-73.993650,40.741543,-73.977974,40.742352,4.0,2015,4,12,6,3
360070,3.7,2011-01-26 19:21:00+00:00,-73.993805,40.724580,-73.993805,40.724577,1.0,2011,1,26,2,19
372609,10.0,2012-10-03 10:40:17+00:00,-73.959160,40.780750,-73.969120,40.761231,1.0,2012,10,3,2,10
550895,8.9,2012-03-14 13:44:27+00:00,-73.952190,40.783950,-73.978645,40.772603,1.0,2012,3,14,2,13
444151,7.3,2012-02-05 15:33:00+00:00,-73.977110,40.746834,-73.991104,40.750403,2.0,2012,2,5,6,15

In [55]:
adddateparts(val_df,'pickup_datetime')

In [56]:
adddateparts(test_df, 'pickup_datetime')

In [57]:
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1.0,2015,1,27,1,13
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986860,40.719383,-73.998886,40.739201,1.0,2015,1,27,1,13
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982520,40.751260,-73.979650,40.746139,1.0,2011,10,8,5,11
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981160,40.767807,-73.990450,40.751635,1.0,2012,12,1,5,21
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966050,40.789776,-73.988560,40.744427,1.0,2012,12,1,5,21
...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955640,40.780388,6.0,2015,5,10,6,12
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945510,40.803600,-73.960210,40.776371,6.0,2015,1,12,0,17
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726610,-73.789740,40.647011,6.0,2015,4,19,6,20
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985570,40.735430,-73.939180,40.801731,6.0,2015,1,31,5,1
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988020,40.754070,-74.000280,40.759220,6.0,2015,1,18,6,14

In [58]:
val_df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
15971,14.00,2015-05-19 09:27:24+00:00,-73.995834,40.759190,-73.973680,40.739086,1.0,2015,5,19,1,9
149839,6.50,2010-04-10 15:07:51+00:00,-73.977390,40.738335,-73.976140,40.751204,1.0,2010,4,10,5,15
515867,49.57,2009-07-25 14:11:00+00:00,-73.983910,40.749470,-73.787170,40.646643,1.0,2009,7,25,5,14
90307,49.70,2011-11-11 19:09:21+00:00,-73.790794,40.643463,-73.972250,40.690180,1.0,2011,11,11,4,19
287032,8.50,2015-03-09 18:06:44+00:00,-73.976590,40.761944,-73.991460,40.750309,2.0,2015,3,9,0,18
...,...,...,...,...,...,...,...,...,...,...,...,...
467556,6.10,2010-04-03 20:16:00+00:00,-73.968570,40.761240,-73.983406,40.750020,3.0,2010,4,3,5,20
19482,7.30,2010-04-26 00:32:00+00:00,-73.986725,40.755920,-73.985855,40.731170,1.0,2010,4,26,0,0
186063,4.50,2009-05-21 08:13:16+00:00,0.000000,0.000000,0.000000,0.000000,1.0,2009,5,21,3,8
382260,32.90,2011-07-07 16:10:59+00:00,-73.980060,40.760334,-73.872590,40.774298,1.0,2011,7,7,3,16
18838,11.50,2015-02-27 12:10:08+00:00,-73.955410,40.782417,-73.960434,40.767666,1.0,2015,2,27,4,12

In [59]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour'],
      dtype='str')

### Add Distance Between Pickup and Drop

In [62]:
import numpy as np

def haversine_np(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)

    All args must be of equal length.

    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(np.sqrt(a))
    km = 6367 * c
    return km

In [63]:
def add_trip_distance(df):
    df['trip_distance'] = haversine_np(df['pickup_longitude'], df['pickup_latitude'], df['dropoff_longitude'], df['dropoff_latitude'])

In [64]:
add_trip_distance(train_df)

In [65]:
add_trip_distance(val_df)

In [66]:
add_trip_distance(test_df)

In [67]:
train_df.sample(5)

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance
6942,16.5,2012-04-06 17:27:00+00:00,0.000000,0.000000,0.00000,0.000000,1.0,2012,4,6,4,17,0.000000
260112,7.0,2012-12-11 19:57:00+00:00,-73.993286,40.727840,-73.97675,40.728885,4.0,2012,12,11,1,19,1.397361
539398,4.0,2015-01-06 17:47:53+00:00,-73.972260,40.786510,-73.97732,40.779572,1.0,2015,1,6,1,17,0.880780
89104,5.3,2011-01-19 09:24:07+00:00,-74.006230,40.739983,-73.99149,40.744110,4.0,2011,1,19,2,9,1.323056
529131,6.5,2013-01-05 13:46:00+00:00,-73.977520,40.759064,-73.98504,40.757932,5.0,2013,1,5,5,13,0.645365

### Add Distance From Popular Landmarks

- JFK Airport
- LGA Airport
- EWR Airport
- Times Square
- Met Meuseum
- World Trade Center

We'll add the distance from drop location.

In [68]:
jfk_lonlat = -73.7781, 40.6413
lga_lonlat = -73.8740, 40.7769
ewr_lonlat = -74.1745, 40.6895
met_lonlat = -73.9632, 40.7794
wtc_lonlat = -74.0099, 40.7126

In [69]:
def add_landmark_dropoff_distance(df, landmark_name, landmark_lonlat):
    lon, lat = landmark_lonlat
    df[landmark_name + '_drop_distance'] = haversine_np(lon, lat, df['dropoff_longitude'], df['dropoff_latitude'])

In [70]:
%%time
for a_df in [train_df, val_df, test_df]:
    for name, lonlat in [('jfk', jfk_lonlat), ('lga', lga_lonlat), ('ewr', ewr_lonlat), ('met', met_lonlat), ('wtc', wtc_lonlat)]:
        add_landmark_dropoff_distance(a_df, name, lonlat)

CPU times: total: 156 ms
Wall time: 151 ms

In [71]:
train_df.sample(5)

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance,jfk_drop_distance,lga_drop_distance,ewr_drop_distance,met_drop_distance,wtc_drop_distance
71663,14.0,2014-05-08 13:24:48+00:00,-74.010124,40.720720,-73.982635,40.737891,1.0,2014,5,8,3,13,2.999928,20.303522,10.119811,17.032049,4.894195,3.629186
141339,6.9,2009-12-03 20:32:45+00:00,-73.969696,40.757523,-73.950150,40.784087,1.0,2009,12,3,3,20,3.379313,21.489259,6.457289,21.617887,1.215345,9.402635
288519,16.5,2012-12-19 18:38:12+00:00,-73.973830,40.758810,-73.991440,40.750043,1.0,2012,12,19,2,18,1.773869,21.658952,10.325354,16.821797,4.036333,4.441751
185180,6.9,2012-05-25 08:12:02+00:00,-73.959230,40.762980,-73.973274,40.752903,1.0,2012,5,25,4,8,1.628324,20.596153,8.770678,18.353665,3.064124,5.437873
512305,10.1,2011-08-14 11:55:00+00:00,-73.987610,40.755280,-73.985440,40.732447,1.0,2011,8,14,6,11,2.543889,20.195037,10.602009,16.624992,5.543347,3.017921

### Remove Outliers and Invalid Data

There seems to be some invalide data in each of the following columns:

- Fare amount
- Passenger count
- Pickup latitude & longitude
- Drop latitude & longitude

In [73]:
train_df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance,jfk_drop_distance,lga_drop_distance,ewr_drop_distance,met_drop_distance,wtc_drop_distance
count,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000,441960.000000
mean,11.354714,-72.498636,39.910002,-72.508144,39.937865,1.684444,2011.740038,6.263920,15.732492,3.035813,13.506568,19.751764,193.147913,182.365314,191.412131,177.416159,178.902025
std,9.789793,11.795326,8.464263,12.398610,9.857420,1.344170,1.857024,3.434881,8.697374,1.950033,6.517710,371.299307,1223.614844,1226.672151,1228.515204,1228.388578,1228.487276
min,-52.000000,-1183.362800,-3084.490200,-3356.729700,-2073.150613,0.000000,2009.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.305573,0.116411,0.129419,0.031102,0.009143
25%,6.000000,-73.992030,40.734860,-73.991410,40.733968,1.000000,2010.000000,3.000000,8.000000,1.000000,9.000000,1.212416,20.535113,8.351080,16.502551,2.169950,3.642450
50%,8.500000,-73.981820,40.752613,-73.980170,40.753078,1.000000,2012.000000,6.000000,16.000000,3.000000,14.000000,2.116182,21.201986,9.575781,18.016146,3.818191,5.559563
75%,12.500000,-73.967186,40.767006,-73.963715,40.768045,2.000000,2013.000000,9.000000,23.000000,5.000000,19.000000,3.879615,21.948134,11.122132,19.953126,6.071881,7.814363
max,400.000000,2420.209500,404.900000,2467.752700,3351.403027,208.000000,2015.000000,12.000000,31.000000,6.000000,23.000000,16913.445559,15057.674680,15074.643087,15074.714519,15077.613263,15072.109456

In [74]:
test_df.describe()

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance,jfk_drop_distance,lga_drop_distance,ewr_drop_distance,met_drop_distance,wtc_drop_distance
count,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000
mean,-73.974722,40.751041,-73.973657,40.751743,1.671273,2011.815816,6.857979,16.194170,2.852834,13.467420,3.433216,20.916635,9.675327,18.546455,4.513050,6.037547
std,0.042774,0.033542,0.039072,0.035435,1.278747,1.803347,3.353272,8.838482,1.994451,6.868584,3.969885,3.303941,3.295654,4.035823,4.018426,4.252531
min,-74.252190,40.573143,-74.263245,40.568973,1.000000,2009.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.402059,0.285418,0.284719,0.085473,0.040565
25%,-73.992500,40.736125,-73.991250,40.735254,1.000000,2010.000000,4.000000,9.000000,1.000000,8.000000,1.297058,20.513193,8.311823,16.520015,2.126165,3.669829
50%,-73.982325,40.753050,-73.980015,40.754065,1.000000,2012.000000,7.000000,16.000000,3.000000,15.000000,2.215799,21.181214,9.477776,18.024041,3.698596,5.541350
75%,-73.968013,40.767113,-73.964061,40.768757,2.000000,2014.000000,10.000000,25.000000,5.000000,19.000000,4.043060,21.909496,10.965804,19.880044,5.922874,7.757275
max,-72.986534,41.709557,-72.990970,41.696683,6.000000,2015.000000,12.000000,31.000000,6.000000,23.000000,99.933652,134.497596,126.062283,149.400500,130.346712,138.619226

We'll use the following ranges:

- `fare_amount`: \$1 to \$500
- `longitudes`: -75 to -72
- `latitudes`: 40 to 42
- `passenger_count`: 1 to 6

In [78]:
def remove_outliers(df):
    return df[(df['fare_amount'] >= 1.) &
              (df['fare_amount'] <= 500.) &
              (df['pickup_longitude'] >= -75) &
              (df['pickup_longitude'] <= -72) &
              (df['dropoff_longitude'] >= -75) &
              (df['dropoff_longitude'] <= -72) &
              (df['pickup_latitude'] >= 40) &
              (df['pickup_latitude'] <= 42) &
              (df['dropoff_latitude'] >=40) &
              (df['dropoff_latitude'] <= 42) &
              (df['passenger_count'] >= 1) &
              (df['passenger_count'] <= 6)]

In [79]:
train_df = remove_outliers(train_df)

In [80]:
val_df = remove_outliers(val_df)

In [82]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'jfk_drop_distance', 'lga_drop_distance', 'ewr_drop_distance',
       'met_drop_distance', 'wtc_drop_distance'],
      dtype='str')

In [83]:
train_df.sample(5)

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance,jfk_drop_distance,lga_drop_distance,ewr_drop_distance,met_drop_distance,wtc_drop_distance
237822,5.7,2009-05-23 19:32:00+00:00,-73.957770,40.761300,-73.944860,40.779008,1.0,2009,5,23,5,19,2.247825,20.772445,5.967404,21.744937,1.543880,9.189221
170528,8.9,2009-08-23 23:11:00+00:00,-74.008480,40.710785,-74.004070,40.742475,1.0,2009,8,23,6,23,3.541084,22.111532,11.597377,15.515092,5.354531,3.355970
175024,7.7,2011-12-23 16:13:00+00:00,-73.981766,40.768080,-73.960304,40.763013,3.0,2011,12,23,4,16,1.892071,20.458522,7.425406,19.801998,1.837244,6.987338
51828,5.7,2012-03-18 15:09:40+00:00,-73.956870,40.780010,-73.946390,40.799829,1.0,2012,3,18,6,15,2.372331,22.610520,6.602092,22.784684,2.674684,11.069824
326025,19.5,2013-03-08 15:32:29+00:00,-73.953720,40.770435,-74.006850,40.749065,1.0,2013,3,8,4,15,5.063475,22.690544,11.601666,15.594519,4.986061,4.060309

NOTE: Scaling and One-Hot Encoding does not helps the tree base model in improving its performance(only when all the columns as numerical value not categorical), if there are categorical data present then scaling and One-Hot Encoding the data is mandatory because the tree base models does not understand the categories like (City = (Delhi, Mumbai, Chennai))

In [84]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'jfk_drop_distance', 'lga_drop_distance', 'ewr_drop_distance',
       'met_drop_distance', 'wtc_drop_distance'],
      dtype='str')

### Save Intermediate DataFrames

Let's save the processed datasets in the Apache Parquet format, so that we can load them back easily to resume our work from this point.

You may also want to create differnt notebooks for EDA, feature engineering and model training.

In [90]:
train_df.to_parquet(r'C:\Users\RISHABH\OneDrive\Desktop\My_Learning\ML with python and sciket_learn\Lesson 7 - Machine Learning Project from Scratch\model_training_data\train.parquet')

In [91]:
val_df.to_parquet(r'C:\Users\RISHABH\OneDrive\Desktop\My_Learning\ML with python and sciket_learn\Lesson 7 - Machine Learning Project from Scratch\model_training_data\val.parquet')

In [92]:
test_df.to_parquet(r'C:\Users\RISHABH\OneDrive\Desktop\My_Learning\ML with python and sciket_learn\Lesson 7 - Machine Learning Project from Scratch\model_training_data\test.parquet')